- test/integration.test.js
Error messages changed in nearcore
> Update expected error msg in a test

- .gitlab-ci.yml
- scripts/generate_js_transaction_proto.sh
Goes with https://github.com/nearprotocol/nearcore/pull/946
> Change path to the proto in nearcore

- dev.js
Just adding dev account funding with default param set.
> update dev account funding

- account.js
- near.js
- nearclient.js
- test/integration.test.js
Extract common transaction encoding/signing/submission code into separate method
> Expose method to send tokens

- nearclient.js
- protos-utils.js
This prevents minifiers from butchering logic.
> Re-write transaction class -> field mapping

- lib/account.js
- lib/transaction.d.ts
- lib/transaction.js
- src.ts/account.ts
- src.ts/transaction.ts
Works with https://github.com/nearprotocol/nearcore/pull/1212
> Add transaction replay protection

- lib/account.js
- lib/key_stores/unencrypted_file_system_keystore.d.ts
- lib/key_stores/unencrypted_file_system_keystore.js
- lib/near.js
- lib/signer.js
- package.json
- src.ts/account.ts
- src.ts/key_stores/unencrypted_file_system_keystore.ts
- src.ts/near.ts
- src.ts/signer.ts
Support `secret_key` and `private_key` field in the key files because we use different format in nearcore and nearlib.
> Better error handling for missing keys and better support for key files

- src.ts/contract.ts
> Add enumerable to contracts

- lib/utils/web.js
- src.ts/utils/web.ts
Ref: https://github.com/nearprotocol/nearcore/issues/1316
> Keep-alive (reuse) connections running in NodeJS environment to reduce the number of new connections

- lib/account.js
- lib/providers/json-rpc-provider.d.ts
- lib/providers/json-rpc-provider.js
- lib/providers/provider.d.ts
- src.ts/account.ts
- src.ts/providers/json-rpc-provider.ts
- src.ts/providers/provider.ts
Required after https://github.com/nearprotocol/nearcore/pull/1544
> Change tx status to use the new API

- lib/account.js
- src.ts/account.ts
Fixes https://github.com/nearprotocol/nearlib/issues/111
> Remove confusing log message about missing public key

- lib/providers/provider.d.ts
- package.json
- src.ts/providers/provider.ts
- test/account.test.js
- yarn.lock
Tests are executing against `nearcore` `staging` branch and we are failing with. But in the same time, we can't merge https://github.com/nearprotocol/nearcore/pull/1715 into `staging` cause CI fails to run test of nearlib (it uses master). How to resolve this ?
> Remove LOG: prefix from log message in test

- test/account.test.js
Unblocks https://github.com/nearprotocol/nearcore/pull/1871. Will need to update nearcore version to 0.4.11 in staging.
> Change version in afterversion

- src.ts/providers/provider.ts
Related to: https://github.com/nearprotocol/nearcore/pull/1934
> Update outcome status position

- gen_error_types.js
- lib/generated/rpc_error_schema.d.ts
- lib/generated/rpc_error_schema.json
- lib/generated/rpc_error_types.d.ts
- lib/generated/rpc_error_types.js
- src.ts/generated/rpc_error_schema.json
- src.ts/generated/rpc_error_types.ts
- test/utils/rpc-errors.test.js
In https://github.com/nearprotocol/nearcore/pull/1854 we decided to rename some errors for consistency. This PR just updates schema and generated classes.
> RPC errors update

- lib/account.d.ts
- lib/account.js
- src.ts/account.ts
- test/account.access_key.test.js
This enables using Account in read-only mode.
> Change the way access key is fetched by Account

- lib/res/error_messages.json
- src.ts/res/error_messages.json
> ReceiverMismatch error message #234

- lib/res/error_messages.json
- src.ts/res/error_messages.json
> RequiresFullAccess incorrect description fix

- src/wallet-account.ts
- test/wallet-account.test.js
Context: submitting premium message stopped working in guest book example after testnet update. No idea why it worked before (shouldn't have worked).
> Add test and fix the mishandling of function call with deposit attached

- .editorconfig
This file tells properly-configured editors how to configure indentation for this project. See https://editorconfig.org/#download
> style: add .editorconfig

- test/config.js
Goodbye nearprotocol.com, hello near.org
> refactor: point test/config.js at near.org

- package.json
- test/account.test.js
- yarn.lock
Fix cross contract test to make sure that it works with master of nearcore. Currently the amount of gas passed to the call exceeds maximum prepaid gas.
> fix cross contract test

- .travis.yml
- lib/key_stores/browser_local_storage_key_store.d.ts
- lib/key_stores/browser_local_storage_key_store.js
- lib/key_stores/in_memory_key_store.d.ts
- lib/key_stores/in_memory_key_store.js
- lib/key_stores/merge_key_store.d.ts
- lib/key_stores/merge_key_store.js
- lib/key_stores/unencrypted_file_system_keystore.d.ts
- lib/key_stores/unencrypted_file_system_keystore.js
- lib/signer.d.ts
- lib/signer.js
- lib/transaction.js
- src/key_stores/browser_local_storage_key_store.ts
- src/key_stores/in_memory_key_store.ts
- src/key_stores/merge_key_store.ts
- src/key_stores/unencrypted_file_system_keystore.ts
- src/signer.ts
- src/transaction.ts
- test/config.js
https://github.com/near/devx/issues/244
> Remove mentions of devnet, since it's no longer running

- test/account.access_key.test.js
Add more allowances to access key in test to make it work with https://github.com/nearprotocol/nearcore/pull/3028
> more allowances in test

- lib/providers/json-rpc-provider.js
- lib/providers/provider.d.ts
- lib/providers/provider.js
- src/providers/json-rpc-provider.ts
- src/providers/provider.ts
Remove `adaptTransactionResult` which is used to support a change that dates back to over an year ago
> fix: remove legacy code

- lib/signer.d.ts
- lib/signer.js
- src/signer.ts
- test/account_multisig.test.js
> add fromKeyPair

- lib/account.d.ts
- lib/account.js
- lib/utils/rpc_errors.d.ts
- lib/utils/rpc_errors.js
- src/utils/rpc_errors.ts
- test/account.test.js
- test/utils/rpc-errors.test.js
Looks like it can be returned in a different format
> Fix nonce error handling

- lib/providers/json-rpc-provider.d.ts
- lib/providers/json-rpc-provider.js
- lib/providers/provider.d.ts
- src/providers/json-rpc-provider.ts
- src/providers/provider.ts
- test/providers.test.js
> Gas price method added to provider

- lib/wallet-account.js
- src/wallet-account.ts
- test/wallet-account.test.js
closing https://github.com/near/near-api-js/issues/195
> requestSignIn throws error if contractId does not exist

- .github/workflows/stale.yml
See more details about this action: https://github.com/marketplace/actions/close-stale-issues
> Add stale PRs action to the workflow

- lib/browser-connect.d.ts
- lib/browser-connect.js
- lib/connect.js
- package.json
- yarn.lock
> bump bn version number to 5.1.0 to match types

- lib/account_multisig.d.ts
- lib/account_multisig.js
- lib/providers/index.d.ts
- src/account_multisig.ts
- src/providers/index.ts
This is expected to make 2FA requests a bit faster (do not block for delete) and more robust (@mattlockyer's change fixes race condition).
> 2FA robustness improvements

- src/account.ts
- src/account_multisig.ts
- src/providers/provider.ts
The 'public_key' should be a string
Signed-off-by: Raymond Feng <enjoyjava@gmail.com>
> fix: fix AccessKeyInfoView type

- lib/account.d.ts
- lib/account_multisig.js
- lib/providers/provider.d.ts
Let's not forget to run `yarn build` before pushing :)
> build artifacts updated

- lib/account.d.ts
- lib/account.js
- src/account.ts
> Document createAndDeployContract amount param

- lib/account_multisig.d.ts
- lib/account_multisig.js
- lib/providers/json-rpc-provider.d.ts
- lib/providers/json-rpc-provider.js
- src/account_multisig.ts
- src/providers/json-rpc-provider.ts
- test/account.access_key.test.js
- test/account.test.js
- test/account_multisig.test.js
- test/promise.test.js
- test/providers.test.js
- test/wallet-account.test.js
> remove deprecated calls

- lib/wallet-account.js
- src/wallet-account.ts
Discovered during support in discord. Matches the NEPs: https://github.com/near/NEPs/blob/17af66e32a83e0bfea4e8110b59902daf09e7ab4/specs/RuntimeSpec/Transactions.md#validation-with-state
> updat error to NotEnoughAllowance from NotEnoughBalance

- .travis.yml
- dangerfile.ts
- package.json
- yarn.lock
Fixes: https://github.com/near/near-api-js/issues/630
Check the comment below to see an example of how it works.
I will make an additional test with fake PR after the merge.
> Danger setup

- examples/cookbook/utils/verify-signature.js
Removes unnecessary `connect` import.
> update verify signature example

- test/account.test.js
As a reference it is blocking: https://github.com/near/nearcore/pull/4579
due to: https://buildkite.com/nearprotocol/nearcore/builds/2580
> bug(test): remove old versioning which is unused in nearcore nodes

- examples/cookbook/transactions/get-tx-detail.js
Fixes #659. Looks to be working after switching over the rpc endpoint:
```
...
working... 9jBCVWg5resUcVgph2YdQXpivDyXCBGq8Cn3m5SxuJbh
working... DZYL6v8ANESE9SoQ4HHkckPSpQk71DGKeaMeVXbJhK81
working... 2XtDDPGiPc9BhiN8ck8efQiWiKonLZgMaaRjDkHwUEHV
working... GZ8vKdcgsavkEndkDWHCjuhyqSR2TGnp9VDZbTzd6ufG
MATCHING TRANSACTIONS:  [
{
actions: [ [Object] ],
hash: '6YRJMXDtZSAZSdZrUnYcuZSfrVKzH1QHeQBBQwUwVjhM',
nonce: 238411,
public_key: 'ed25519:4K28jzn9YEzMR2v8J4UQmzbrL6H5kDSqxAKdZaWvQHJt',
receiver_id: 'client.ropsten.testnet',
signature: 'ed25519:2evUKBknAcsEvgjxvAcUb8r7iNZMZBkq5mQsJ8hhAwEfnXeyr94vTvWof5XsLkgpA8kdHKjA6UTwaRsCYDG9D2xo',
signer_id: 'relayer.ropsten.testnet'
},
{
actions: [ [Object], [Object] ],
hash: 'CJKdeHET5TvTf31cAWpeKNB6uHouSK3FLvfV3RsHSxp4',
nonce: 238410,
public_key: …
```
> fix: get-tx-detail example now uses archival rpc endpoint

- test/config.js
Reverts near/near-api-js#682
Explained reasoning: https://github.com/near/sdk-docs/pull/49#issuecomment-930227241
cc: @volovyk-s @bowenwang1996 @EgorKulikov @RNHTTR
> Revert "Fix bug in config.js for localnet"

- jest.config.js
- lib/account.js
- lib/connect.js
- lib/utils/errors.d.ts
- lib/utils/errors.js
- lib/utils/index.d.ts
- lib/utils/index.js
- lib/utils/web.js
- src/account.ts
- src/connect.ts
- src/utils/errors.ts
- src/utils/index.ts
- src/utils/web.ts
'NEAR_NO_LOGS ' is used to disable printing internal logs  and errors.
> fix: disable internal logging with env variable

- lib/wallet-account.js
- package.json
- yarn.lock
We need this dependency to merge https://github.com/near/near-api-js/pull/723
> Husky dep added

- examples/cookbook/utils/check-account-existence.js
This has come up a few times and I think is a good cookbook example
> Add cookbook item to check for existence of account

- lib/utils/web.js
- src/utils/web.ts
Closing #750 (check the issue for details).
> charset utf-8 deleted from request header

- lib/near.js
- src/near.ts
- test/providers.test.js
> near.deps check added

- lib/account.d.ts
- lib/account.js
- lib/account_multisig.d.ts
- lib/account_multisig.js
- lib/common-index.d.ts
- lib/common-index.js
- lib/providers/json-rpc-provider.d.ts
- lib/providers/json-rpc-provider.js
- lib/providers/provider.d.ts
- lib/wallet-account.d.ts
- lib/wallet-account.js
- src/account.ts
- src/account_multisig.ts
- src/common-index.ts
- src/providers/json-rpc-provider.ts
- src/providers/provider.ts
- src/wallet-account.ts
- test/providers.test.js
- test/wallet-account.test.js
- typedoc.json
Let's delete all deprecated code before designing wallet-selector (lots of API affected) and  1.0 release.
FYI: this PR is targeting `release-1.0` branch, not `master`.
> Deletion of deprecated func

- lib/wallet-account.d.ts
- lib/wallet-account.js
- src/wallet-account.ts
fix misspelling in [the documentation](https://near.github.io/near-api-js/classes/walletaccount.walletconnection.html#requestsigntransactions)
> fix: typo `isSingnedIn` -> `isSignedIn`

- lib/providers/provider.d.ts
- src/providers/provider.ts
Reference Issue Link is below.
Closes #815
> modify interface Transaction in provider.ts

- lib/account.d.ts
- lib/account.js
- lib/account_multisig.d.ts
- lib/account_multisig.js
- lib/common-index.d.ts
- lib/common-index.js
- lib/connect.js
- lib/near.d.ts
- lib/near.js
- lib/providers/json-rpc-provider.d.ts
- lib/providers/json-rpc-provider.js
- lib/providers/provider.d.ts
- lib/wallet-account.d.ts
- lib/wallet-account.js
- src/account.ts
- src/account_multisig.ts
- src/common-index.ts
- src/connect.ts
- src/near.ts
- src/providers/json-rpc-provider.ts
- src/providers/provider.ts
- src/wallet-account.ts
- test/providers.test.js
- test/test-utils.js
- test/wallet-account.test.js
- typedoc.json
Preparation for 1.0 release.
Should be merged before #785
> Deprecated functionality deleted

- examples/quick-reference.md
> Fixed typo in quick reference docs

- .github/pull_request_template.md
PR templates will create consistency with open source contributions and provide pre-requsite steps for submissions. Closes: #728 
This PR adds a pull request template to the repository.
> chore: Create Pull Request template

- .changeset/fresh-fans-protect.md
- .github/dependabot.yml
- packages/cookbook/utils/unwrap-near.js
- packages/near-api-js/fetch_error_schema.js
- packages/near-api-js/package.json
- pnpm-lock.yaml
Fixed linter bugs, like as variable _is assigned a value but never used_
> fix: remove never used variables

- package.json
- packages/biometric-ed25519/.eslintrc.yml
- packages/biometric-ed25519/README.md
- packages/biometric-ed25519/package.json
- packages/biometric-ed25519/src/fido2.js
- packages/biometric-ed25519/src/index.d.ts
- packages/biometric-ed25519/src/index.ts
- packages/biometric-ed25519/src/utils.ts
- packages/biometric-ed25519/tsconfig.json
- pnpm-lock.yaml
This PR contains implementation of web 3 authentication with biometric.
> Web3 Authentication with biometric finger print [EDD-18]

- packages/biometric-ed25519/package.json
> chore: bump version for pnpm publishing

- .changeset/hip-ligers-drive.md
- packages/accounts/src/contract.ts
> make contract method interface optional

- .devcontainer/devcontainer.json
Closes #1119
Create a codespaces session from this branch in-browser and see for youself:) It works!!
Closes #1119
> feat: create devcontainer.json

- .changeset/light-wombats-wink.md
- packages/accounts/src/account.ts
- packages/near-api-js/src/transaction.ts
- packages/transactions/src/delegate.ts
> feat: signed delegate workarounds

- .changeset/long-badgers-smile.md
- packages/biometric-ed25519/src/index.ts
- packages/biometric-ed25519/src/utils.ts
Removes username length limit from biometric-ed25519 code
> fix: remove username length check, format code

- .github/ISSUE_TEMPLATE/epic-template.md
- .github/ISSUE_TEMPLATE/issue-template.md
Added two new templates as per the standard process.
> Update issue templates

- packages/accounts/test/providers.test.js
This PR fixes the broken integration tests
fixes #1197
> fix: remove fields missing from response

- docs/README_TYPEDOC.md
- packages/accounts/src/account_2fa.ts
- packages/signers/README.md
- packages/utils/src/validators.ts
https://github.com/near/near-api-js/pull/1065
> Update broken links

- packages/accounts/CHANGELOG.md
- packages/near-api-js/CHANGELOG.md
fix a typo: `Compatiblity`->`Compatibility`
> chore: fix typos

- .changeset/khaki-paws-bow.md
- packages/providers/src/failover-rpc-provider.ts
- packages/providers/src/json-rpc-provider.ts
- packages/providers/src/provider.ts
- packages/types/src/provider/index.ts
> Fix TxExecutionStatus import

- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- .github/workflows/typedoc-generator.yml
> ci: update pnpm/action-setup to v4

- .changeset/clean-cougars-jump.md
- packages/iframe-rpc/src/iframe-rpc.ts
- packages/keystores-browser/src/index.ts
- packages/keystores-browser/src/multi_contract_browser_local_storage_key_store.ts
- packages/keystores-browser/test/browser_keystore.test.js
- packages/keystores-browser/test/multi_contract_browser_keystore_common.js
- packages/keystores/src/index.ts
- packages/keystores/src/multi_contract_keystore.ts
> feat: MultiContractKeystore (rebased)

- .changeset/tasty-meals-cover.md
> Bump package versions

- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- .github/workflows/typedoc-generator.yml
- Matches the same version in #1460 
- Fixes broken GitHub Actions in `master`
> fix(ci): update pnpm version in GitHub Action

- .github/workflows/typedoc-generator.yml
* pnpm needs to be initialized first - oops.
> fix(ci): fix pnpm intialization for typedoc action

- .changeset/rotten-cases-dance.md
> Fix changeset configuration for Major release V6

- .changeset/eight-chairs-taste.md
- packages/accounts/src/account.ts
> Redeploy recent major release as patch via CI/CD

- .changeset/real-llamas-smile.md
> fix: changesets version

- .changeset/all-lions-happen.md
> fix: reduce the severity of change in #1556 to patch

- .changeset/quick-snakes-shout.md
- packages/accounts/package.json
- packages/biometric-ed25519/package.json
- packages/keystores-browser/package.json
> Include `@near-js/*` packages into `peerDependencies` of each individual package

- .github/workflows/pull-request.yml
- README.md
- e2e/.npmrc
- e2e/package.json
- e2e/pnpm-lock.yaml
- e2e/tests/accounts.test.ts
- e2e/tests/worker.ts
- e2e/tsconfig.json
- e2e/vitest.config.ts
- package.json
This Pull Request adds end-to-end tests to `@near-js/*` that are set up to make sure the packages work the same way real applications would use them. These tests go beyond just checking individual functions - they make sure the packages can be properly installed, imported, built, and run in actual project setups
Fixes https://github.com/near/near-api-js/issues/1571
> Add end-to-end tests

- .changeset/dry-clocks-tap.md
- packages/near-api-js/package.json
- packages/near-api-js/src/utils/errors.ts
- packages/near-api-js/tsup.config.ts
- pnpm-lock.yaml
> Move to building `near-api-js` with `tsup` as the rest of the packages in the workspace

- .changeset/config.json
- .changeset/wide-schools-remain.md
- package.json
- pnpm-lock.yaml
> Bump `near-api-js` to catch up with the rest of packages

- .changeset/icy-news-send.md
- .changeset/rotten-eagles-rest.md
- packages/accounts/src/account.ts
- packages/accounts/src/utils.ts
- packages/client/src/view.ts
- packages/providers/src/failover-rpc-provider.ts
- packages/providers/src/json-rpc-provider.ts
- packages/providers/src/provider.ts
- packages/types/src/provider/response.ts
> Add generic response types to some functions of `Account` and `Provider`
