near/near-api-js

lib/providers/json-rpc-provider.d.ts
lib/providers/json-rpc-provider.js
lib/providers/provider.d.ts
src.ts/providers/json-rpc-provider.ts
src.ts/providers/provider.ts
test/providers.test.js

Ref: https://github.com/nearprotocol/nearcore/pull/1524

Exposed `chunk` RPC API (nearcore 0.4.2+)

---

lib/transaction.d.ts
lib/transaction.js
src.ts/transaction.ts
test/serialize.test.js

Change signTransaction to take transaction object so that transaction signing can be separated from transaction creation.

Change signTransaction to take transaction object

---

src.ts/contract.ts
test/account.test.js

Fixes https://github.com/nearprotocol/nearlib/issues/117

Allow creation of contracts with only view or change methods

---

lib/account.d.ts
lib/account.js
lib/transaction.d.ts
src.ts/account.ts
src.ts/contract.ts
src.ts/transaction.ts

Set to 1/1000 of current `REACT_APP_ACCESS_KEY_FUNDING_AMOUNT` on testnet. 
So app can do 1000 transactions with default access key allowance.
Fixes https://github.com/nearprotocol/nearlib/issues/176

Increase default gas amount for function calls

---

lib/res/error_messages.json
lib/utils/rpc_errors.js
src.ts/res/error_messages.json
src.ts/utils/rpc_errors.ts
test/utils/rpc-errors.test.js

fixes https://github.com/nearprotocol/nearlib/issues/206
fixes https://github.com/nearprotocol/nearlib/issues/210
The problem was that serde serialize Enums differently:
for variants with data it serialize it as an object with a key which corresponds to a variant and value with data, but in case of variants w/o data it serializes as just a string. 
This checks if the key is a string and we have it in the schema.

Fix for empty error variants

---

test/utils/format.test.js

This uses Jest's `test.each` ([docs]) to format these tests as tables, which makes them easier to visually parse
Other improvements:
* remove unused & invalid `toFail()` matcher, replacing it with `toThrowError`
* remove unnecessary `async`s
[docs]: https://jestjs.io/docs/en/api#testeachtablename-fn-timeout

refactor: clean up format tests

---

lib/near.js
src.ts/near.ts

**Problem**: Commands that use `masterAccount` will fail with gas errors. This includes `near-shell` commands like `dev deploy`. See the issue opened by Illia: https://github.com/nearprotocol/near-shell/issues/271.
A simple way to reproduce this is to use `create-near-app` and run a `dev-deploy`
`npx create-near-app my-awesomely-broken-app`
install dependencies…
use `near login` for an account XYZ_NEAR.
then:
`near dev-deploy --masterAccount XYZ_NEAR`
You'll see this error:
> The account dev-123… wouldn't have enough balance to pay required rent 10920
Odd because that rent is super low.
There are a series of issues. The first issue is here:
https://github.com/nearprotocol/nearlib/blob/master/src.ts/near.ts#L25
We recently wrapped the `initialBalance` in a `BN()` which is from the `bn.js` …

fund account created with masterAccount with proper gas

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Addresses: https://github.com/nearprotocol/nearlib/issues/228
This is a request that came in a while ago. This repo already had a LICENSE. Slightly customized the testing section in `CONTRIBUTING.md` to refer to the `README.md` that nicely lays this out already.

add code of conduct, contributing markdown files

---

.travis.yml

Looks like it gets in the way, e.g. these builds fail, but `yarn audit` stops failing after updating `yarn.lock`:
https://travis-ci.com/github/nearprotocol/nearlib/jobs/296530318
https://travis-ci.com/github/nearprotocol/nearlib/jobs/296530604
However it has nothing to do with security of library, as `yarn.lock` from this repo isn't honored when installing library as dependency.

Removing `yarn audit` from CI

---

lib/providers/json-rpc-provider.d.ts
src.ts/providers/json-rpc-provider.ts

We had a discussion about this change here: https://github.com/near/near-api-js/pull/245#discussion_r385943826

feat: Exposed `JsonRpcProvider.sendJsonRpc` method to public to help playing with EXPERIMENTAL_* APIs in nearcore

---

.gitignore
.npmignore
README.md
browser-exports.js
package.json
src/account.ts
src/near.ts
test/account.access_key.test.js
test/account.test.js
test/fuzz/borsh-roundtrip.js
test/key_pair.test.js
test/key_stores/browser_keystore.test.js
test/key_stores/in_memory_keystore.test.js
test/key_stores/keystore_common.js
test/key_stores/merge_keystore.test.js
test/key_stores/unencrypted_file_system_keystore.test.js
test/providers.test.js
test/serialize.test.js
test/signer.test.js
test/test-utils.js
test/utils/format.test.js
test/utils/rpc-errors.test.js
test/wallet-account.test.js

Cherry-picked some stuff from https://github.com/near/near-api-js/pull/287 and changed some other (e.g. using `nearApi` instead of `nearAPIJs`).
Local storage prefix cannot be changed this easily (we would effectively nuke existing accounts in wallet).

Fix remaining nearlib rename quirks

---

browser-exports.js
package.json
src/browser-index.ts
src/key_stores/browser-index.ts
tsconfig.json

This is needed to prevent web bundlers from failing with default config because `fs` module is not found.

Setup separate entry point for browser build

---

README.md

Some grammar & stylistic improvements for the README. Now that this will also be our landing page for API Reference docs (#289), I thought it was important to clarify that these instructions are for contributing to this library itself, not using it. We may also want to add some info about how to use the library soon.

refactor: improve README

---

.github/workflows/docs.yml
package.json
tsconfig.json
yarn.lock

Previously, we were copying the output of `yarn doc` from this repository and commiting it to the `docs` folder in https://github.com/nearprotocol/docs. Since `nearprotocol/docs` is a [docusaurus](https://docusaurus.io/) website, we used `typedoc-plugin-markdown` here in this repository to build documentation in the format expected by docusaurus.
Last week, realizing that this `yarn doc` output is an auto-generated artifact that we don't need to commit into either repository, I looked into automating this whole "build docs, copy to other repository" process; see https://github.com/nearprotocol/docs/pull/291. While attempting to finalize this approach with @amgando, we realized it had multiple issues:
* After about three days of effort, my script still had some major gaps that left the …

serve docs via GitHub Pages

---

lib/index.d.ts
lib/index.js
src/index.ts

`connect` is asynchronous, which limits the ways it can be used. The only reason it's asynchronous is to support `UnencryptedFileSystemKeyStore`. Browser-based apps will not need this.
If an app doesn't use the filesystem, let's give them a way to instantiate a `Near` instance synchronously, without using `connect`.

feat: export Near

---

src/near.ts

Get rid of `any` types so it's more clear what values someone can pass to the `connect` function and the `Near` class

refactor: add types to connect & Near args

---

src/key_stores/browser_local_storage_key_store.ts

This is a follow-up to https://github.com/near/near-api-js/pull/288
As we are about to move our testnet wallet from wallet.nearprotocol.com to wallet.testnet.near.org, we will be breaking many testnet wallet accounts already, so it is a good time to do this cleanup.
BREAKING CHANGE: once an app updates to this version, user data that had been stored in BrowserLocalStorageKeyStore will be lost

rename localStorage key to near-api-js

---

lib/contract.js
src/contract.ts
test/account.test.js
test/contract.test.js

This lays groundwork to improve the ergonomics of https://github.com/near-examples/guest-book/pull/79
Function Binding
----------------
When passing around contract functions throughout an app, I have ended
up in situations where `near-api-js` ends up throwing an error:
TypeError: Cannot read property 'account' of undefined
Using arrow functions ensures correct binding of these functions, so
that `this` refers to what we expect.
`.name` behavior
----------------
If you call `someFunction.name`, JavaScript will show the name of the
function (see [mdn]). However, this doesn't work as expected with
functions defined using `Object.defineProperty`.
Using an approach found on [StackOverflow], this ensures that the
`.name` property works as expected for these contract functions.
Example:
const …

improve usability of contract functions

---

lib/key_stores/unencrypted_file_system_keystore.js
src/key_stores/unencrypted_file_system_keystore.ts
test/key_stores/unencrypted_file_system_keystore.test.js

Currently when we write a `UnencryptedFileSystemKeyStore` to file, we do not write the public key. This can cause problems as ed25519 public key is not recoverable from its private key. Also for nearcore compatibility it would be nice if the private key field is named "secret_key". @vgrichina do we have anything that depends on the field's name?

add public_key field to key file

---

lib/account.js
lib/providers/json-rpc-provider.js
src/account.ts
src/providers/json-rpc-provider.ts

This is needed because nearcore fails to return proper structured error:
https://github.com/nearprotocol/nearcore/issues/1839
Related to https://github.com/near/near-api-js/issues/127
Fixes https://github.com/near/near-api-js/pull/280

Fix retry on Timeout error

---

lib/key_stores/unencrypted_file_system_keystore.d.ts
lib/key_stores/unencrypted_file_system_keystore.js
src/key_stores/unencrypted_file_system_keystore.ts
test/key_stores/unencrypted_file_system_keystore.test.js

If application changes the path, keystore stops to work as it recorded a relative path.
This updates to record absolute path at the creation and leverage that during the app lifetime.

Record current directory in file system keystore

---

lib/account.js
lib/key_stores/in_memory_key_store.d.ts
lib/key_stores/in_memory_key_store.js
lib/key_stores/merge_key_store.d.ts
lib/key_stores/merge_key_store.js
lib/key_stores/unencrypted_file_system_keystore.d.ts
lib/key_stores/unencrypted_file_system_keystore.js
lib/signer.d.ts
lib/signer.js
src/account.ts
src/key_stores/in_memory_key_store.ts
src/key_stores/merge_key_store.ts
src/key_stores/unencrypted_file_system_keystore.ts
src/signer.ts
test/account.access_key.test.js

Makes error messages from Signer more useful:
> Can not sign transactions for account lockup.vg on network deDault, no matching key pair found in InMemorySigner(MergeKeyStore(UnencryptedFileSystemKeyStore(/Users/vg/.near-credentials), UnencryptedFileSystemKeyStore(/Users/vg/Documents/near-genesis/near-claims/neardev))).

Add debug toString to signer and key stores

---

src/near.ts

While not used directly within the `src/near.ts` file, `src/connection.ts` expects this value to be set on this config, and provides no default

docs: add walletUrl to NearConfig type

---

lib/browser-index.js
lib/common-index.js
lib/contract.js
lib/index.js
lib/near.d.ts
lib/utils/index.js
lib/utils/rpc_errors.js
lib/utils/serialize.js
src/contract.ts
test/contract.test.js

Let's say you have a `contract` object instantiated in your code, and the contract it wraps has an `add_person` function which receives a borsh-serialized struct. The following code now works:
import { serialize } from 'near-api-js/lib/utils/serialize'
class Person {
constructor (proof) {
Object.assign(this, proof)
}
}
const personSchema = new Map([
[Person, {
kind: 'struct',
fields: [
['age', 'u64'],
['name', 'String'],
]
}]
])
const person = new Person({ age: 33, name: 'Jesus' })
contract.add_person(serialize(personSchema, person))

feat: allow borsh-serialized contract fn arguments

---

src/account.ts

Currently, we did not hit the corner case since there are only a few accounts that do real stake.
See https://nomicon.io/Economics/README.html#state-stake
```python
def check_storage_cost(account):
requiredAmount = sizeOf(account) * storageAmountPerByte
return Ok() if account.amount + account.locked >= requiredAmount else Error(requiredAmount)
```
and also the matching implementation in nearcore: https://github.com/near/nearcore/blob/a480d6eb3d9c6542100efdc6364eb89daac69383/core/runtime-configs/src/lib.rs#L75-L95
/cc @icerove

fix: fixed the available balance computation when stake is involved

---

lib/account.d.ts
lib/account.js
lib/browser-index.js
lib/common-index.js
lib/contract.js
lib/index.js
lib/utils/index.js
lib/utils/rpc_errors.js
lib/utils/serialize.js
src/account.ts
src/contract.ts
test/account.test.js
test/contract.test.js

Say you have a `contract` object instantiated in your code, and this contract has a `get_age` endpoint which returns a borsh-serialized number. The following code now works:
import {
deserialize as deserializeBorsh
} from 'near-api-js/lib/utils/serialize'
class BorshPerson {
constructor (args) {
Object.assign(this, args)
}
}
const schema = new Map([
[BorshPerson, {
kind: 'struct',
fields: [
['get_age', 'u64']
]
}]
])
function deserializePerson (raw) {
return deserializeBorsh(schema, Person, raw)
}
// a small helper class to wrap a near-api-js Contract instance
export default class Person {
constructor (contract) {
this.contract = contract
}
async getAge () {
const deserialized = await this.contract.get_age(
{},
{ parse: deserializePerson }
)
return deserialized.get_age.toNumber()
}
}

feat: enable view calls to deserialize with borsh

---

lib/account.js
lib/account_multisig.d.ts
lib/account_multisig.js
lib/signer.d.ts
lib/signer.js
src/account.ts
src/account_multisig.ts
src/signer.ts
test/account_multisig.test.js

- fix deployMultisig to only convert full access keys to multisig limited access keys
- fix to Account.addKey where you can add multiple methodNames
- fix to add one off signer from keyPair

hotfix: 2FA key rotations, Account.addKey, InMemorySigner.fromKeyPair

---

lib/account.d.ts
lib/account.js
src/account.ts

This PR adds support for `Account.addKey` that _also_ accepts an array of methodNames vs. just a string of 1 methodName. Matches more closely to how `functionCallAccessKey` works.

add support for multiple methodNames to Account.addKey

---

src/utils/web.ts

Reasons:
- RFC says it's Content-Type, not Content-type
- node-fetch package is checking for the `Content-Type` header in a case sensitive manner and overwrites it when cannot find it https://github.com/node-fetch/node-fetch/blob/master/src/request.js#L71
- because of the node-fetch Content-Type check, the header is sometimes overwritten and near-api-js call is not always recognized as application/json request

fix(utils/web): Fix typo in Content-Type header

---

lib/browser-connect.d.ts
lib/browser-connect.js
lib/browser-index.d.ts
lib/browser-index.js
lib/common-index.d.ts
lib/common-index.js
lib/connect.d.ts
lib/connect.js
lib/index.d.ts
lib/index.js
lib/near.d.ts
lib/near.js
lib/signer.d.ts
lib/signer.js
src/browser-connect.ts
src/browser-index.ts
src/common-index.ts
src/connect.ts
src/index.ts
src/near.ts
src/signer.ts

Fixes https://github.com/near/near-api-js/issues/397

Make sure that webpack build doesn’t end up requiring `fs`

---

lib/account.js
lib/providers/json-rpc-provider.js
src/account.ts
src/providers/json-rpc-provider.ts

This change basically moves existing exponential retry logic from Account deeper.
Also handling `query has timed out` popping up on some endpoints under load.
This fixes multiples problems which are both reported on users and popping up on Sentry (once nearcore RPC is failing under load):
https://sentry.io/organizations/near-protocol/issues/1953747896/?project=5396205&query=is%3Aunresolved&sort=freq&statsPeriod=14d
https://sentry.io/organizations/near-protocol/issues/2124349518/?project=5396205&query=is%3Aunresolved&sort=freq&statsPeriod=14d
https://sentry.io/organizations/near-protocol/issues/1927563464/?project=5396205&query=is%3Aunresolved&sort=freq&statsPeriod=14d
https://sentry.io/organizations/near-protocol/issues/2112717975/?project=5396205&query=is%3Aunresolved&sort=freq&statsPerio …

Implement timeout handling at sendJsonRpc level

---

lib/account.js
lib/providers/json-rpc-provider.js
lib/utils/rpc_errors.d.ts
lib/utils/rpc_errors.js
lib/wallet-account.js
src/account.ts
src/providers/json-rpc-provider.ts
src/utils/rpc_errors.ts
src/wallet-account.ts
test/utils/rpc-errors.test.js

To avoid the situations where we are matching string errors with the use of `match`, `indexOf`, or `includes` we can do this only once in JSON RPC provider.
This logic can be deleted when `nearcore` will start returning typed errors.

Types added to some JSON RPC errors

---

lib/account.d.ts
lib/account.js
lib/near.js
lib/wallet-account.js
src/account.ts
src/near.ts
src/wallet-account.ts
test/account.test.js
test/account_multisig.test.js

This creates extra RPC requests and seems to be there only for historic reasons.

Don't fetch account state pre-emptively

---

src/providers/json-rpc-provider.ts

Most of the links to the documentation for the RPC endpoints were broken and all domain names were outdated.
This PR fixes that.

Fix documentation links for JSON-RPC provider

---

lib/account_multisig.d.ts
lib/account_multisig.js
src/account_multisig.ts
test/account_multisig.test.js

- Pass transaction result back (contract helper requires update to return it) https://github.com/near/near-contract-helper/pull/347
- Only repeat loop on what is explicitly user error (wrong code)

Fix passing result back from 2FA account

---

lib/providers/json-rpc-provider.d.ts
lib/providers/json-rpc-provider.js
lib/providers/provider.d.ts
lib/utils/index.d.ts
lib/utils/index.js
src/providers/json-rpc-provider.ts
src/providers/provider.ts
src/utils/index.ts
src/utils/network.ts

closes #282 
`getNetwork()` deleted from `Provider` interface and `JsonRpcProvider`.
@vgrichina @mikedotexe it's a breaking change, but we don't have any mentions about `getNetwork` in our docs. I have also deleted `Network` interface since it's never used (YAGNI).

getNetwork deleted from Provider

---

src/utils/exponential-backoff.ts

The counter in the loop was incremented twice, effectively halving the
retryNumber.

fix bug in exponentialBackoff

---

lib/browser-connect.d.ts
lib/browser-connect.js
lib/connect.js
lib/utils/setup-node-fetch.d.ts
lib/utils/setup-node-fetch.js
lib/utils/web.js
src/connect.ts
src/utils/setup-node-fetch.ts
src/utils/web.ts

Fixes #415 and removes a todo.
Adds the import of `node-fetch` into a separate module and attaches `node-fetch` to `global` only in the node import path.

remove node-fetch added to global in node env

---

lib/account.js
src/account.ts
test/account.test.js

Fixes #559
Right now if you try to send multiple transactions before caching an access key you will run into nonce errors (which will automatically retry the transaction) or you will create multiple of the exact same transaction like in the linked issue.
What we want to do is lock on `findAccessKey` so that we only trying to find an access key one at a time for a public key. But, in JavaScript land this seem to not be a common approach.
Instead, this PR checks before returning the access key to see if it has already been cached while the network call was in flight.

Check cache for access key after network request

---

lib/connect.d.ts
lib/connect.js
lib/key_stores/merge_key_store.d.ts
lib/key_stores/merge_key_store.js
src/connect.ts
src/key_stores/merge_key_store.ts

See #469
From @mikedotexe 
> I've noticed this on and off and finally figured out it's a one-liner.
When I create a function-call access key for an account and then specify it as the keyPath, the full access key was being used.
When a person specifies the keyPath, I believe that means, "Please use this keystore first, as I'm specifying to use it." Instead it's added to the end of the MergeKeyStore, so it's the last keystore to be checked.
This simply flips that so the first keystore used is the one specified by keyPath.
Keep in mind this comment: https://github.com/near/near-api-js/pull/469#issuecomment-772398493
> keyPathStore is an InMemoryKeyStore. It gets precedence so all new keys are written to it. So if you e.g. try to create new account while specifying keyPath to provide key for …

Adding keyPath uses that keystore first

---

lib/account.d.ts
lib/account.js
lib/providers/json-rpc-provider.js
src/providers/json-rpc-provider.ts

Right now if a jsonrpc returns this result:
```
{"jsonrpc":"2.0","result":"","id":1}
```
near-api-js consider it as fail and retry until timeout. This behavor is incorrect. According to jsonrpc spec, Valid success jsonrpc can respond empty result, such as `""` or `null`, for example in sandbox_patch_state rpc and adversarial rpcs. Valid error response should be determined by `result` key not present or `error` key is present.
Also exponentialBackoff won't return if result is "" or null, so make this return entire json rpc response to avoid it keep retry on `{..., result: ""}` response and only retry on real error response and fetch errors

fix: jsonrpc empty string response should success

---

examples/cookbook/README.md
examples/cookbook/transactions/get-tx-status.js

Adds an example of getting a transaction status by hash. This was prompted by a [community request in Discord](https://discord.com/channels/490367152054992913/817102046725406780/852735491198418994).

add get tx status example

---

test/providers.test.js

See this failing test: https://buildkite.com/nearprotocol/nearcore/builds/1547#2c89c279-4fd8-490d-8235-86531597f5d3
`tx` method was extended with one more field (`receipts`), which is not a breaking change, but the output of the broadcast_tx_commit does not return `receipts` (only returns `status`, `transaction`, `transaction_outcome`, and `receipts_outcome`), so we need to check if the response from `broadcast_tx_commit` is a strict subset of the `tx` response.

feat: prepare tests for the stabilization of `EXPERIMENTAL_tx_status` method

---

lib/wallet-account.js
src/wallet-account.ts

This allows app to request login (and get account name of the user) without adding access key for a contract.

Shouldn't check if account exists if `contractId` not passed

---

.npmignore
package.json

Our releases on NPM contain config files, tests, and example code snippets. Let's use whitelisting instead of `.npmignore` file.
I'm wondering if we should remain `src` folder. Can we assume that everybody is using `lib` only?
`src` folder is ~180 kByte's, it would be cool to get rid of it and reduce loading time in all our apps.
Also, it's not clear for me how  `dist/near-api-js.min.js` works and how it should be used. There are no mentions of it in our docs.

Release files whitelisted

---

lib/providers/json-rpc-provider.js
src/providers/json-rpc-provider.ts
test/providers.test.js

use block_id in rpc query

---

examples/cookbook/package.json

Rather than using version published to NPM, the `examples/cookbook` folder can use the version of NAJ from the root of the project.

build: cookbook uses root NAJ

---

examples/cookbook/utils/wrap-near.js

Fixes #655 
* Take CLI arguments instead of requiring script modification
* Add  HELP constant to file top, log it if script invoked incorrectly
* Use parseNearAmount for `storage_deposit` call to fix borsh/BN issue

fix(examples/wrap-near): docs, serialization

---

README.md

Typedocs have 404 errors from the main README.md file for quickstart and cookbook. [See here](https://near.github.io/near-api-js/) This PR updates these links to have the full URL instead of pathing from the root directory.
Fixes https://github.com/near/devrel/issues/293

update links to cookbook and quickstart

---

.eslintrc.yml
lib/account.d.ts
lib/account.js
lib/transaction.d.ts
lib/transaction.js
src/account.ts
src/transaction.ts

Add support for custom way to stringify arguments.
The motivation was to support borsh both in view & call functions.
The implementation is based on @MaximusHaximus suggestion at https://github.com/near/near-api-js/pull/620#discussion_r656438592

Borsh in view

---

examples/cookbook/README.md
examples/cookbook/transactions/batch-transactions.js
examples/cookbook/utils/deploy-contract.js

Fixes #683 
- Went through all cookbook examples and fixed batch-transaction and deploy-contract to incorporate dirname in order to make it so that the user can run the scripts regardless of their terminal directory. 
- Fixed readme instructions

Added ability to call cookbook files regardless of terminal directory

---

test/config.js

When running locally, `nearup` creates a validator_key.json file at `~/.near/localnet/nodeN/validator_key.json`, where N is 0, 1, 2, or 3 by default.
When the environment is set to `local`, `near-api-js` [is looking for](https://github.com/near/near-api-js/blob/master/test/config.js#L27-L33) validator_key.json to be at `~/.near/validator_key.json`. This results in a `KeyNotFound` error when trying to call `near create-account`
Detailed steps to reproduce can be found [in this PR for documentation for running contracts on localnet](https://github.com/near/sdk-docs/pull/49/files?short_path=407a45a#diff-407a45ad5884e51f51a5294ddf4ef06229add5a276170c6e664e09efe9f2f262) (ctrl/cmd + f and search for "bug in nearup" to see where the bug occurs.)
near-cli 2.1.1
nearup 1.2.0

Fix bug in config.js for localnet

---

lib/providers/json-rpc-provider.js
src/providers/json-rpc-provider.ts
src/utils/errors.ts
test/providers.test.js

We have a small breaking change that I want to fix in this PR.
Somebody requested a change in this issue: https://github.com/near/near-api-js/issues/635
And it was fixed in this PR: https://github.com/near/near-api-js/pull/639
Now, when we are passing `block_id` instead of the suggested `blockId`, it's becoming `undefined`.
I think that our API should be consistent and we should support only `block_id`, so I'm basically reverting the PR mentioned above.

block_id fix

---

lib/providers/json-rpc-provider.js
lib/wallet-account.js
src/providers/json-rpc-provider.ts

Now when trying a transaction the warning can be ignore.  It was very log and made the output of workspace tests very noisy.

fix: add check to suppress retry log

---

lib/validators.d.ts
lib/validators.js
src/validators.ts
test/validator.test.js

Appeared that it can be done in a none breaking way, but we need to provide extra parameters.
As an option, I can add a completely new function that will get that data for us.
Something like:
```javascript
export async function getSeatPrice(validators);
``` 
Or even:
```javascript
export async function getSeatPrice(CURRENT/NEXT);
```
But I'm not sure if it's flexible enough.

New findSeatPrice implementation

---

.husky/pre-commit
lib/wallet-account.js
package.json

issue: #701 
Added git hook using `Husky` package . 
Since this PR doesn't have `package.json` file , so to make husky work run the below command:
`yarn add husky --dev`
and paste this in `package.json` file:
```
{
"scripts": {
"prepare": "husky install"
}
}
```
[Husky documentation](https://typicode.github.io/husky/#/)

Added git hook

---

lib/account.d.ts
lib/account.js
lib/account_multisig.d.ts
lib/wallet-account.d.ts
src/account.ts
src/account_multisig.ts
src/wallet-account.ts
test/test-utils.js

Playing with separation of Account logic. It should help to be more flexible and pass signing to the wallet/walletSelector.  More info in comments.

Account, WalletConnection and ConnectedWalletAccount interfaces

---

lib/account_multisig.d.ts
lib/account_multisig.js
src/account_multisig.ts

This PR adds a `disableWithFAK` method to the `Account2FA` class. This method will allow 2fa disable to be performed without calling the multisig contract if a FAK is loaded into the keystore. It will optionally clear the account state using the [state cleanup contract](https://github.com/near/core-contracts/tree/master/state-cleanup) if the bytes are provided.
If no FAK is loaded into the keystore, the method will throw a `NoFAKFound` error.
`disableWithFAK` will be used on a script that is intended to restore accounts with bricked multisig with a seedphrase.

feat: add method to disable 2FA with FAK

---

.github/workflows/stale.yml

Many contributors have noted that 7 days of no activity is too short for marking a PR as stale.  
See 
#792 
#793 
#788
#800 
#801 
I know that @volovyk-s is doing his best to keep up with the demands of making things compatible with the new Dev Console and other "frontier" tools, but it is sad that community contributions are languishing.

fix: make PR stale after 14 days of no activity

---

examples/quick-reference.md

Updating the Call Contract method with a callbackUrl using the example from https://github.com/near/near-api-js/blob/master/src/contract.ts

Adding calbackUrl and meta to Call Contract

---

lib/providers/json-rpc-provider.d.ts
lib/providers/json-rpc-provider.js
lib/providers/provider.d.ts
src/providers/json-rpc-provider.ts
src/providers/provider.ts
test/providers.test.js

This MR is fixing a fundamental error in the TS wrapper fro txStatusReceipts which should accept both Uint8Array or string and accordingly execute the EXPERIMENTAL_tx_status JSON rpc request.

Fix for json-rpc method EXPERIMENTAL_tx_status

---

lib/wallet-account.d.ts
lib/wallet-account.js
src/wallet-account.ts
test/wallet-account.test.js

This should fix https://github.com/near/near-api-js/issues/817 and closes #857 this problem 
also it will help apps understand that keys are ready and can be used after login callback

Be able to await until sign in process done completely

---

lib/account.js
src/account.ts
test/account.access_key.test.js

[Issue-618](https://github.com/near/near-api-js/issues/618)
Added more tailored error throws on `signTransaction`  where if depends on either `publicKey` or `accessKey` is missing, throw error with mentioning which one is missing.
1. Make sure that near-cli is installed but logged out state.
2. Change `require("near-api-js");` to `require("../../../lib/index");` on `examples/cookbook/transactions/batch-transactions.js`
3. Run this commend from root:
```
yarn run build
cd examples/cookbook/transactions
node batch-transactions.js
```

Update error throws on signTransaction

---

packages/near-api-js/src/wallet-account.ts
packages/near-api-js/test/wallet-account.test.js

This PR attempts to address server side devX for the `WalletConnection` class per #801 by returning a proxy that intercepts gets on the instance and throws an explicit error if it's a function call or returns predictable values preventing unpredictable errors and behaviors on SSR stacks and Node.js.

feat: explicit walletconnection errors on server

---

package.json

Provide transparency for the users, which version of node runtime you support
Updated `engines` property inside package.json with node version greater or equal to 16.16.0 to be enforced.

Applied engines property on package.json

---

packages/near-api-js/src/account.ts
packages/near-api-js/test/account.test.js

[Issue-627](https://github.com/near/near-api-js/issues/627)
Users wanting to use `viewFunction` call as if they are using `functionCall`.
By passing single object that contains all arguments as props. This is actually standard practice compared to passing multiple props in specific order. 
Created adapter layer where depends on the format of given arguments, it either deconstruct from object (new approach) or passing given arguments as it is (existing approach)

feat: changed viewFuction to support both POJO and existing arguments

---

packages/near-api-js/src/providers/json-rpc-provider.ts
packages/near-api-js/src/utils/rpc_errors.ts
packages/near-api-js/test/account.access_key.test.js
packages/near-api-js/test/utils/rpc-errors.test.js

Delete https://github.com/near/near-api-js/blob/master/src/utils/rpc_errors.ts#L88 and other hacks related to Error handling and types as error types are now available on `near-core`.
- Remove `getErrorTypeFromErrorMessage` and every usage of it.
- Pass error type directly with `response.error.name`
- Remove related tests

NAJ-113-delete-hacks-related-to-error-types

---

packages/near-api-js/src/near.ts

So that folks can construct a `Near` instance without providing `headers`
Updates `headers` in TS `NearConfig` type to optional

fix(near-api-js): optional headers in NearConfig

---

packages/near-api-js/src/wallet-account.ts
packages/near-api-js/test/wallet-account.test.js

It fixes issue #325 
Describe the changes made in this PR. How does it solve the above?
It fixes the appKeyPrefix by checking it's coming as undefined.

Fixed appKeyPrefix undefined value

---

packages/near-api-js/src/wallet-account.ts
packages/near-api-js/test/wallet-account.test.js

Reverts near/near-api-js#927
While this isn't buggy, we'd like to improve the following and release a better version in 1.1:
1. [Not unnecessarily delete and recreate the key in localStorage if the new and old key are the same](https://github.com/near/near-api-js/pull/927/files/40e049b3ee19c00bd80d21c0890f84da2ab04d44#r953147205)
2. [More test cases especially around migrating storage from old to new authDataKey](https://github.com/near/near-api-js/pull/927#discussion_r953151759) (migration is only relevant when old appKeyPrefix is `undefined_..` and new `appKeyPrefix` is `default_..`)
3. Refactor the `WalletConnection` constructor to make it easier to reason about `authDataKey` and `DEPRECATED_authDataKey` possibly by moving them to the top of the block and having clear conditions

Revert "Fixed appKeyPrefix undefined value"

---

package.json
packages/near-api-js/package.json
yarn.lock

Builds/publishing were failing due to un-met peer dependencies caused by recent upgrade of TS versions.
- Updated typedoc to latest version, which supports TS 4.7.x
- Modified `engines` to 16.14 as this is the latest version supported by the newest typedoc version

chore: update typedoc to support latest TS version

---

packages/near-api-js/src/wallet-account.ts

According to this (https://docs.near.org/docs/tutorials/front-end/naj-examples#the-wallet-interface) getAccountId() should return a string.

refactor(near-api-js): getAccountId() returns a string.

---

packages/near-api-js/src/transaction.ts

Closes #587 
This PR no longer sends a `nonce` when adding an access key since this is set at the protocol level and the sent value is ignored.

refactor(near-api-js): remove unnecessary nonce from AccessKey

---

packages/near-api-js/src/account.ts

NAJ-61
This case can occurred (typeof result.status.Failure === 'object' can process on Failure object in case of null). Fixed!

fix: NAJ-61

---

packages/near-api-js/src/account.ts
packages/near-api-js/src/providers/provider.ts
packages/near-api-js/src/transaction.ts
packages/near-api-js/src/wallet-account.ts
packages/near-api-js/test/serialize.test.js

#220 
This PR contains implementations to migrate number typed nonce to string.
Added a string type check to throw error if `nonce` with `number` is given.
Updated all existing tests

Migrating nonce type from number to string

---

.github/workflows/release.yml

Changeset action takes `createGithubReleases` (plural) rather than `createGithubRelease`
Updates the changeset workflow to use the correct key

fix: typo in changeset release workflow

---

.changeset/beige-suits-march.md
.changeset/lazy-candles-hide.md
.gitignore
packages/near-api-js/src/account.ts
packages/near-api-js/src/account_multisig.ts
packages/near-api-js/src/wallet-account.ts
packages/near-api-js/test/account.test.js
packages/near-api-js/test/account_multisig.test.js

NAJ-44
Make `Account.signAndSendTransaction` public so transactions can be sent directly from Account instances

Naj 44 make sign and send transaction functionality public

---

.changeset/beige-suits-march.md
.gitignore
packages/near-api-js/src/account.ts
packages/near-api-js/src/account_multisig.ts
packages/near-api-js/src/wallet-account.ts
packages/near-api-js/test/account.test.js
packages/near-api-js/test/account_multisig.test.js

Reverts near/near-api-js#1002
Doing this so we can release the minor/patch changes first and then commit to a major bump.

Revert "Naj 44 make sign and send transaction functionality public"

---

.changeset/beige-suits-march.md
.gitignore
packages/near-api-js/src/account.ts
packages/near-api-js/src/account_multisig.ts
packages/near-api-js/src/wallet-account.ts
packages/near-api-js/test/account.test.js
packages/near-api-js/test/account_multisig.test.js

Reverts near/near-api-js#1005
https://github.com/near/near-api-js/pull/1002 was reverted so we could temporarily avoid a major bump of `near-api-js`

Revert "Revert "Naj 44 make sign and send transaction functionality public""

---

.changeset/great-jobs-destroy.md
packages/cookbook/utils/wrap-near.js
packages/near-api-js/src/account.ts
packages/near-api-js/src/account_multisig.ts
packages/near-api-js/src/contract.ts
packages/near-api-js/test/account.test.js
packages/near-api-js/test/contract.test.js

This PR is removing old syntax that is expected to be deprecated. Since this PR contains BREAKING CHANGE, prior to merge, please follow up with team to confirm correct schedule. 
This PR will update `viewFunction` in `account.ts` to only support single object as argument. (Deprecating on supporting old convention of accepting array of arguments)
Also updates existing tests

Update viewFunction with only accepting single object as argument

---

.changeset/wild-teachers-marry.md
packages/near-api-js/src/providers/json-rpc-provider.ts
packages/near-api-js/src/utils/rpc_errors.ts
packages/near-api-js/test/account.access_key.test.js
packages/near-api-js/test/utils/rpc-errors.test.js

This is a partial restoration of changes from #910 . At this moment near-api-js is not returning proper error types for errors: `AccountDoesNotExist`, `AccessKeyDoesNotExist`, `CodeDoesNotExist`, `InvalidNonce`. Issue: #980 .
1. Restoring `getErrorTypeFromErrorMessage` function, with a default value change. The previous implementation was always returning `UntypedError` if the error message doesn't match pointed strings, which means it could possibly change the type even if it already exists, which was not ideal - this function should return the proper type if it matches, and don't change the type if not matches. If the request doesn't have a type at all, we have a proper condition to change the type if it doesn't exist in the `TypedError` class.
2. Restoring usage of …

fix: error types

---

packages/near-api-js/src/account.ts
packages/near-api-js/src/utils/logging.ts

This PR moves the `printLogs` and `printLogsAndFailures` private methods out of the `Account` class and into independent functions under `/utils`.
This is the first step towards refactoring the transaction signing/sending behavior out of the `Account` class hierarchy.

refactor: remove log/debug methods from `Account` class

---

.changeset/gentle-points-shake.md
packages/near-api-js/src/wallet-account.ts
packages/near-api-js/test/wallet-account.test.js

Alternative approach to key migration implemented in #947 . Closes #325 
Makes `appKeyPrefix` a required arg to `WalletConnection` constructor
Users that were doing
```typescript
new WalletConnection(near);
```
will now have to do
```typescript
new WalletConnection(near, "undefined");
```
If they want to access the keys they had potentially accumulated

feat!: make appKeyPrefix required

---

.changeset/slimy-baboons-itch.md

This PR updates the changeset from to the packages refactor to omit new packages. Including them is not the expected behavior, making the change log unnecessarily difficult to interpret.

docs: omit new packages from changeset file

---

.changeset/sixty-cycles-itch.md
.github/workflows/release.yml

This PR updates the `release` workflow to call `pnpm build` prior to publishing. The refactor PR removed the `prepare` script, which was implicitly called previously.

ci: add explicit build before publishing

---

.changeset/soft-days-type.md
.github/workflows/release.yml

This PR reverts to usage of `NPM_TOKEN` for publishing the `near-api-js` package

ci: partial revert to use near-api-js NPM key

---

.changeset/smooth-moons-brush.md
packages/providers/src/provider.ts

- ✅ I have read the [Contributing Guidelines on pull requests](https://github.com/near/near-api-js/blob/master/CONTRIBUTING.md).
- ✅ Commit messages follow the [conventional commits](https://www.conventionalcommits.org/) spec
- ✅ **If this is a code change**: I have written unit tests.
- ✅ **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

fix: fix validators function to accept null to show latest block info

---

.changeset/dry-bulldogs-develop.md
packages/providers/src/fetch_json.ts

Fixes #1109 
NodeJS tests passing ensures that no changes will affect that environment. Browser bundles will similarly continue to function the same way as this change does not change evaluation order of `global.fetch`. React Native environments will now be able to import `@near-js/providers`.
Fixes #1109

fix: dynamically import module with native node dependencies

---

.changeset/real-plums-suffer.md
packages/iframe-rpc/.eslintrc.yml
packages/iframe-rpc/README.md
packages/iframe-rpc/package.json
packages/iframe-rpc/src/iframe-rpc-error.ts
packages/iframe-rpc/src/iframe-rpc.ts
packages/iframe-rpc/src/index.ts
packages/iframe-rpc/src/types.ts
packages/iframe-rpc/tsconfig.json
pnpm-lock.yaml

Implements initial cut of iframe-rpc package for discovery fastauth usage

feat: add iFrame RPC package initial implementation

---

.changeset/rotten-monkeys-tie.md
packages/accounts/test/providers.test.js
packages/near-api-js/test/providers.test.js
packages/types/src/provider/response.ts

This RPC type is missing fields that are required for proof verification. There is another `metadata` field and `compute_usage` fields that are missing also, but I opted to keeping these changes light.
I defaulted to having this be a patch changeset, but can change to minor if intended. Unclear how semver is with TS adding fields to interfaces (esp in this case since those types shouldn't be constructed manually)
updated an existing test

fix: add missing fields to execution outcome and test

---

.changeset/slimy-fans-tan.md
packages/near-api-js/src/connect.ts
packages/wallet-account/src/near.ts

This PR enables the use of a `deps` argument to `NearConfig` instances. This restores legacy usage of passing in `deps.keyStore` instead of passing in `keyStore` as a top level argument to the configuration instance.
NB if both `keyStore` and `deps.keyStore` are passed, `keyStore` will continue to be used.
The test plan involves updating to the latest `near-api-js` and verifying that signing still works when the `deps` parameter is used. Locally this was tested with `cookbook` examples, verifying that when `deps.keyStore` is used in place of `keyStore` there is no change in functionality.

Restore deps key

---

.changeset/grumpy-kids-yell.md
packages/biometric-ed25519/src/index.ts

This PR fixes a bug with the `getKeys` method in the biometric-ed25519 package. This method is currently broken due to not awaiting an async function and trying to access undefined properties on the promise.
Tested locally. Future e2e tests should be written using playwright

fix: add await to recoverPublicKey

---

.changeset/short-lions-learn.md
packages/transactions/src/actions.ts

For enum deserialization, only the field that matches the pattern will be defined, where the other fields will not be set. These types incorrectly indicate through the type that all fields are defined, which is not correct.
Likely this should be more than a patch release since breaking, but just opening this PR more as a suggestion (I don't need for anything, just noticed when reading code).

fix: update enum field types to optional to match functionality

---

.changeset/two-jobs-perform.md
packages/biometric-ed25519/package.json
packages/biometric-ed25519/src/fido2.ts
pnpm-lock.yaml

This PR contains fixes and improvements for fido2 part of biometric-ed25519.
- Upgrade fido2-lib to 3.4.1 (latest)
- Updated `authenticatorUserVerification` attribute of fido2 from 'discouraged' to 'preferred'
(https://www.w3.org/TR/webauthn-2/#enum-userVerificationRequirement)
- Updated `cryptoParams` attribute of fido2 to include `RS256` algorithm which is accepted on android (by adding `-257` )
https://www.w3.org/TR/webauthn-2/#typedefdef-cosealgorithmidentifier
I have manually tested above change within near-discovery + using android studio on mac environment to simulate the android experience.
N/A

Bugfix and improvements on biometric-ed25519 package

---

.changeset/wet-jars-attend.md
packages/near-api-js/src/connect.ts
packages/providers/src/fetch_json.ts

Feel free to help me get tests passing!
Ticket: #1193
Attempting to use the node native fetch API in node >= 18 when the near-api-js is imported directly or by a transitive dependency results in the node global fetch property being overwritten by near-api-js.
These two lines of code [here](https://github.com/near/near-api-js/blob/53ba3f21c6da503e971a251b205bf50ea8b36dd0/packages/near-api-js/src/connect.ts#L31) and [here](https://github.com/near/near-api-js/blob/53ba3f21c6da503e971a251b205bf50ea8b36dd0/packages/providers/src/fetch_json.ts#L32) explicitly override the global fetch property.
They should not do this.
I am not sure how to test this. Suggestions welcome
#1193

fix: remove global override of `fetch`

---

.changeset/funny-jars-camp.md
packages/accounts/src/account.ts
packages/near-api-js/src/connect.ts
packages/providers/src/fetch_json.ts
packages/providers/src/json-rpc-provider.ts
packages/utils/src/errors/errors.ts
packages/utils/src/logging.ts

To prevent error 'process undefined' in environments where global process object does not exist
Fixes issue whereby importing module in environments without a global `process` object would throw error `process undefined`.
1) Wrote small Vitejs app with `"near-api-js": "."` dependency.
2) `vite` threw `process undefined` in browser console
3) Added change, `vite` no longer threw error in browser console
Closes #737

fix: add check for process global to exist

---

.changeset/nice-worms-arrive.md
packages/biometric-ed25519/package.json
packages/biometric-ed25519/src/index.ts

This PR contains small change on `biometric-ed25519` package where upon creating passkey from the browser, sometimes it is possible that `navigator.credentials.create({ publicKey })` code can return null and it breaks the flow without being handled. 
There was an [issue](https://github.com/near/fast-auth-signer/issues/55) reported and discussed that reflect the outcome of this PR. 
(I have locally imported this change and run account creation flow on `fast-auth-signer` repo and it shows `alert` as expected)
[issue](https://github.com/near/fast-auth-signer/issues/55)

feat: handling null response from navigator.credentials.create

---

.changeset/spicy-tomatoes-talk.md
packages/accounts/package.json
packages/accounts/src/account.ts
packages/accounts/test/providers.test.js
packages/biometric-ed25519/package.json
packages/biometric-ed25519/src/index.ts
packages/crypto/package.json
packages/crypto/src/key_pair_ed25519.ts
packages/crypto/src/public_key.ts
packages/crypto/test/key_pair.test.js
packages/near-api-js/package.json
packages/near-api-js/src/utils/serialize.ts
packages/providers/package.json
packages/providers/src/json-rpc-provider.ts
packages/transactions/package.json
packages/transactions/src/action_creators.ts
packages/transactions/src/actions.ts
packages/transactions/src/create_transaction.ts
packages/transactions/src/schema.ts
packages/transactions/test/serialize.test.js
packages/utils/package.json
packages/utils/src/format.ts
packages/wallet-account/package.json
packages/wallet-account/src/wallet_account.ts
packages/wallet-account/test/wallet_account.test.js
pnpm-lock.yaml

We have developed a new version of `borsh-js` which is agnostic to the `Class` being (de)serialized. This means that two "deep equal" objects can be (de)Serialized using the same Schema, no matter their origin or particular Class.
I have updated the dependency of `borsh-js` and changed the code as minimal as possible until all the tests passed again.
Fixes #1167

feat: update borsh-js to v1.0.0

---

.changeset/healthy-bees-shout.md
packages/providers/src/fetch_json.ts

Non-mainnet networks may experience instability and return 408 HTTP errors, which could delay testing/development. However, this can be fixed by retrying requests.
made https://github.com/near/near-api-js/pull/989 working without merge conflicts by minor code change

Retry RPC requests on 408 HTTP error

---

.github/workflows/typedoc-generator.yml

The current workflow is not automatically building the docs
Tested it on a personal repo: https://github.com/gagdiez/near-lake-framework-js/commit/12857a22d526e88703248806947bf98b10e7c1ec

fix: allow workflow to write content

---

.changeset/tasty-spoons-visit.md
packages/crypto/package.json
packages/crypto/src/key_pair_ed25519.ts
pnpm-lock.yaml

After the last update(3.0.0), wallet.requestSignIn functionality has been broken. The goal of this PR is to fix this problem by adding crypto-browserify package which is a port of node's crypto module to the browser. 
Tested by running this project https://github.com/kujtimprenkuSQA/simple-naj-demo with the changes from this PR.
https://github.com/near/near-api-js/issues/1218

Add crypto-browserify

---

.changeset/swift-plums-marry.md
packages/crypto/package.json
packages/crypto/src/key_pair_ed25519.ts
pnpm-lock.yaml

`crypto-browserify` includes a lot of dependencies that aren't helpful for our use case - generating randombytes. That's why it's replaced with `randombytes`. `randombytes` is used by a lot of web3 apps like MetaMask, Trezor, etc. It's also a fraction of `crypto-browserify`'s size (1.6kb vs 238.2kb). This change will lead to significant size reduction of NAJ.
#1221

Replace crypto-browserify with randombytes

---

.changeset/afraid-gorillas-stare.md
packages/biometric-ed25519/package.json
packages/biometric-ed25519/src/index.ts
packages/biometric-ed25519/src/utils.ts
packages/crypto/test/key_pair.test.js
packages/near-api-js/package.json
packages/near-api-js/src/browser-index.ts
packages/signers/package.json
packages/signers/src/in_memory_signer.ts
packages/transactions/package.json
packages/transactions/src/sign.ts
pnpm-lock.yaml

Reuse noble-hashes instead of js-sha256 to reduce the amount of dependencies.
Reuse noble-curves instead of elliptic to reduce the amount of dependencies.
Remove error-polyfill package since it is no longer used explicitly.
All tests pass
https://github.com/near/near-api-js/pull/1217
https://github.com/near/near-api-js/issues/1200

Replace and remove dependencies with lighter and audited alternatives

---

.changeset/gold-peas-applaud.md
packages/biometric-ed25519/src/index.ts

fix: pass the correct parameter to getPublicKey() in getKeys()

---

.changeset/twelve-rabbits-cough.md
packages/wallet-account/src/wallet_account.ts
packages/wallet-account/test/wallet_account.test.js

Some use cases certainly require not redirecting instantly to the Wallet page
The following methods were added to the WalletConnection class that construct URL without calling `window.assign` afterward:
* `requestSignInUrl`
* `requestSignTransactionsUrl`
Deprecated PR -> https://github.com/near/near-api-js/pull/1025
Issue -> https://github.com/near/near-api-js/issues/1010

Introduce methods to construct URLs to the wallet without instant redirect

---

.changeset/silly-queens-dream.md
packages/crypto/src/key_pair_ed25519.ts

In a client-side environment, `KeyPairEd25519.fromRandom()` throws `TypeError: unexpected type, use Uint8Array`. The goal of the PR is to fix this problem by passing the secret key as a Uint8array to the `getPublicKey()` method.
All existing tests pass.

KeyPairEd25519.fromRandom() fix

---

.changeset/cuddly-plants-wave.md
packages/biometric-ed25519/package.json
packages/biometric-ed25519/src/index.ts
packages/biometric-ed25519/src/utils.ts
packages/providers/test/providers.test.js
pnpm-lock.yaml

All tests pass.
https://github.com/near/near-api-js/issues/1248

Biometric-ed25519 package bug fix

---

.changeset/little-chefs-decide.md
packages/accounts/src/account.ts
packages/accounts/src/connection.ts
packages/accounts/src/contract.ts
packages/accounts/src/index.ts
packages/accounts/src/interface.ts
packages/accounts/src/local-view-execution/index.ts
packages/accounts/src/utils.ts
packages/accounts/test/contract.test.js
packages/accounts/test/contract_abi.test.js

Many developers complained about the confusing implementation of the Contract class, which requires an Account parameter in the constructor even for view function calls
This PullRequest solves the issue by extending the interface of the first parameter in the constructor and additionally **enables full backward compatibility** with older versions
```js
// account is required
const contract = new Contract(account, options);
contract.view_method({});
contract.call_method({});
```
```js
const contract = new Contract(connection, options);
// no account required
contract.view_method({});
// signerAccount must be specified to sign the transaction
contract.call_method({ signerAccount: account });
```
https://github.com/near/near-api-js/pull/1066 …

Extend Contract class to enable view function calls without Account

---

.changeset/mighty-paws-tap.md
packages/biometric-ed25519/src/index.ts
packages/biometric-ed25519/src/utils.ts

This PR contains fixes for #1330 issue. The main reason why passkey did not work with BitWarden was because they do not follow standard format for [webauthn credentials](https://www.w3.org/TR/webauthn-2/#iface-pkcredential) in which they used data format of `Uint8Array` instead of `ArrayBuffer`. However they can be easily convert-able so in this PR I have implemented logic to do the conversion.  
On https://github.com/near/fast-auth-signer/ repo, run it locally with commend `yarn && NETWORK_ID=testnet yarn run start --https` (Bitwarden only works with https)
On new Chrome browser profile, install Bitwarden chrome extension package. 
manually navigate to localhost:3000/create-account and try to create an account.
(At this point, you should be able to replicate the issues)
Apply the above …

biometric-ed25519 update to support BitWarden password manager

---

.changeset/shiny-coats-fly.md
packages/accounts/src/connection.ts
packages/cookbook/api-keys/backup-provider.js
packages/near-api-js/src/providers/failover-rpc-provider.ts
packages/near-api-js/src/providers/index.ts
packages/providers/src/failover-rpc-provider.ts
packages/providers/src/index.ts
packages/providers/src/json-rpc-provider.ts
packages/providers/test/providers.test.js
packages/wallet-account/package.json
packages/wallet-account/src/near.ts
pnpm-lock.yaml

RPC providers can experience intermittent downtime, connectivity issues, or rate limits that cause client transactions to fail. This could have been prevented if near-api-js had the `FailoverRpcProvider` that supports multiple RPC providers.
```js
const jsonProviders = [
new JsonRpcProvider({
url: 'https://rpc.mainnet.near.org',
}),
new JsonRpcProvider(
{
url: 'https://another-rpc.cloud.com',
headers: { 'X-Api-Key': 'some string' },
},
{ retries: 3, backoff: 2, wait: 500 }
),
];
const provider = new FailoverRpcProvider(jsonProviders);
await connect({
networkId: 'mainnet',
provider: provider,
// this isn't used if `provider` is specified, but is still required for backward compativility
nodeUrl: 'https://rpc.mainnet.near.org',
});
```
https://github.com/near/near-api-js/pull/1216 …

Introduce `FailoverRpcProvider` that switches between providers in case of a failure of one of them

---

.changeset/chilly-coats-sniff.md
.github/workflows/release.yml
packages/biometric-ed25519/package.json
packages/biometric-ed25519/src/index.ts
packages/biometric-ed25519/src/utils.ts
packages/biometric-ed25519/test/utils.test.js
pnpm-lock.yaml

This PR contains bug fix that are introduced on #1331. When it was locally tested, it worked as expected. However we have recently received a feedback that it breaks existing flow. (Possibly from recent Chrome browser change perhaps?)
After further investigation, I have confirmed that existing approach would not work because 'Credentials' (A.K.A  PublicKeyCredential) is a non-enumerable object where it doesn't allow to apply `Object.keys()`. 
Since existing 'sanitization' is tailored for specific purpose (convert Uint8Array to ArrayBuffer), decided to tailor the function for its needs by explicitly checks for expected response properties from `navigator.credentials.create` and  `navigator.credentials.get`.
One thing to note on current approach is that if we encounter `Credentials` …

biometric-ed25519 bug fix on supporting Bitwarden

---

.changeset/silver-chicken-kiss.md
packages/providers/src/json-rpc-provider.ts
packages/types/src/provider/protocol.ts

Update tx execution status

---

.changeset/fast-books-stare.md
packages/utils/src/errors/error_messages.json
packages/utils/src/errors/rpc_error_schema.json
packages/utils/test/rpc-errors.test.js

With protocol version 68, cross-shard congestion control is introduced that adds two new errors on the RPC endpoints for submitting transactions. (ShardCongested, ShardStuck)
Protocol version 69 introduces stateless validation and also adds a new error for submitted transactions. (ReceiptSizeExceeded)
Technically, there are additional errors in nearcore's version of the rpc schema. But those are from nightly features that have not been masked properly. (NonRefundableTransferToExistingAccount  and InvalidTransactionVersion are waiting for NEP-491 and NEP-541 respectively.)
Aside from updating the schema, I also added human readable error messages and tests for the new errors.
Closes #1358
See #1358 
Unit tests in `packages/utils/test/rpc-errors.test.js` check that the new error kinds are …

feat: update RPC error schema for protocol version 69

---

.github/workflows/transfer-to-project.yml

x## Pre-flight checklist
Adds issues and PRs to the DevTools github project for tracking purposes.

feat: adds issues and PRs to DevTools proejct

---

packages/cookbook/README.md

Cookbook links in README were all broken due to a file extension mistake (.js instead of .ts)

fix: resolve broken links in cookbook

---

.changeset/neat-crabs-beam.md
packages/accounts/package.json
packages/accounts/test/account.access_key.test.ts
packages/accounts/test/providers.test.ts
packages/near-api-js/package.json
packages/utils/package.json
packages/utils/src/format.ts
pnpm-lock.yaml

This PR switches the Base58 implementation to a [secure, audited & 0-deps implementation](https://github.com/paulmillr/scure-base). The existing `bs58` library is old, poorly maintained, and incompatible with Vite due to its use of Node.js primitives (`Buffer`).
This PR should resolve the following:
* https://github.com/near/near-api-js/issues/1420
* https://github.com/near/near-api-js/issues/1408
* https://github.com/near/near-api-js/pull/1391
* https://github.com/near/near-api-js/pull/1392
> [!NOTE]  
This project still indirectly relies on `bs58` through `near-workspaces`:
```
near-workspaces 3.5.0
├─┬ borsh 0.5.0
│ └── bs58 4.0.0
├── bs58 4.0.1
```

Switch to secure Base58 library

---

.changeset/mean-hotels-matter.md
package.json
packages/accounts/package.json
packages/accounts/src/account_2fa.ts
packages/accounts/src/account_creator.ts
packages/client/package.json
packages/client/src/funded_account.ts
packages/providers/jest.config.ts
packages/providers/package.json
packages/providers/src/fetch_json.ts
packages/providers/test/fetch_json_error.test.ts
packages/tsconfig/base.json
pnpm-lock.yaml

since near-js least supported node version is v20, the polyfill could be safely dropped. React Native, and all edge runtimes all support fetch. There is no need to keep the polyfill anymore.
unit tests
none

Remove unfetch

---

.github/CODEOWNERS
.github/workflows/pull-request.yml
package.json
pnpm-lock.yaml
turbo.json

Improved turbo caching and task configuration
Updated our turbo.json configuration to be more robust and enable better caching:
- Added transit pattern so test/lint tasks properly track dependency changes
- Removed overly restrictive input globs that were skipping important files (package.json, lockfile)
- Added proper caching setup in CI with actions/cache@v4
Also upgraded our toolchain:
- turbo 1.4.5 -> 2.4.2 
- pnpm 9.4.0 -> 10.4.1
- node 20.15.0 -> 20.18.3
- Various GitHub Actions to their v4 versions
The main win here is proper caching - our previous input globs were too restrictive and could miss important dependency changes. As a bonus, the transit pattern makes it safer to run tasks in parallel if needed.

feat(ci): update turbo, add caching

---

.changeset/weak-adults-love.md
packages/client/src/signing/signers.ts

fix: "Cannot mix BigInt and other types" for signing transaction with explicitly provided nonce

---

.changeset/poor-items-study.md
packages/client/src/signing/signers.ts
packages/transactions/test/transaction.test.ts

This PR fixes issues in getSignerFromKeyPair and getSignerFromPrivateKey, where the signer was incorrectly passing a non-hashed encoded transaction to sign().
It also adds non-trivial arguments to the test cases, providing clearer examples for others to reference. (https://github.com/near/near-api-js/issues/1432)

fix: Wrong payload being signed

---

.changeset/all-lions-happen.md
.changeset/config.json
.changeset/easy-areas-hug.md
.changeset/real-llamas-smile.md

This change is meant to fix the issue with `changeset` unnecessarily upgrading all the packages to `major` version, even though they are `minor` changes
This must return the behaviour to expected, which is
- `@near-js/*` goes from `2.0.1` to `2.1.0`
- `near-api-js` goes from `6.0.1` to `6.1.0`

Fix changesets config

---

.changeset/fix-instanceof-signetransaction.md
packages/transactions/src/schema.ts

- Replaced `instanceof SignedTransaction` check with duck typing using `'signature' in transaction`
- Prevents failures when different package versions are used across dependencies
- Maintains same functionality while being more robust
Fixes #1569

Fix instanceof check for SignedTransaction to prevent cross-package errors

---

.changeset/add-waituntil-to-callfunction.md
packages/accounts/src/account.ts

- Add optional `waitUntil` parameter to `callFunction()` method in `@near-js/accounts`
- Allow users to configure transaction finality when calling smart contract functions
- Fully backward compatible - parameter is optional and defaults to `INCLUDED_FINAL`
- Updated `callFunction()` method signature to include `waitUntil?: TxExecutionStatus`
- Pass `waitUntil` parameter through to `signAndSendTransaction()`
- Added JSDoc documentation for the new parameter
```typescript
// Before (still works)
await account.callFunction({
contractId: 'contract.near',
methodName: 'my_method',
args: {}
});
// After (new capability)
await account.callFunction({
contractId: 'contract.near', 
methodName: 'my_method',
args: {},
waitUntil: 'INCLUDED' // Configure transaction finality
});
```
Fixes #1575

Add optional waitUntil parameter to callFunction method

---

.changeset/fix-tokens-exports.md
packages/tokens/.gitignore
packages/tokens/package.json
packages/tokens/tsup.config.ts
pnpm-lock.yaml

Fixes export configuration issues in `@near-js/tokens` package that were causing installation errors and limiting usage of nested imports.
Closes #1582
- Remove invalid `"build": "workspace:*"` dependency from devDependencies
- This was causing npm install errors: "No matching version found for build@0.0.0"
- All nested exports now work with Node16+, ESM, CJS, and bundlers
**Before:**
```
"@near-js/tokens/mainnet"
node10: 💀 Resolution failed
"@near-js/tokens/testnet"  
node10: 💀 Resolution failed
```
**After:**
```
"@near-js/tokens/mainnet"
node16+: 🟢 All resolution modes work
"@near-js/tokens/testnet"  
node16+: 🟢 All resolution modes work
```
Note: Node10 resolution failures for nested exports are expected since this project requires Node 20.18.3+
With these changes, users can now …

fix(tokens): improve export configuration and remove invalid dependency

---

.github/workflows/pull-request.yml
package.json
turbo.json

Add workflow step to check that packages are configured properly for CJS, ESM and older environments

---

.changeset/cool-buses-wonder.md
packages/accounts/src/account.ts

Set default `waitUntil` value back to `EXECUTED_OPTIMISTIC`

---

.changeset/angry-buttons-search.md
.changeset/cute-tires-fall.md
.changeset/easy-trains-serve.md
packages/providers/src/failover-rpc-provider.ts
packages/providers/src/json-rpc-provider.ts
packages/providers/src/provider.ts

Fixes the issue reported by the community of interface misalignment
```
Type 'JsonRpcProvider' is not assignable to type 'Provider'.
The types returned by 'callFunction(...)' are incompatible between these types.
Type 'Promise<T | undefined>' is not assignable to type 'Promise<T>'.
Type 'T | undefined' is not assignable to type 'T'.
'T' could be instantiated with an arbitrary type which could be unrelated to 'T | undefined'.
```

Fix interface misalignment between `Provider` and `JsonRpcProvider`

---

.changeset/angry-planets-send.md
packages/tokens/src/ft/format.ts
packages/tokens/src/ft/index.ts
packages/tokens/test/fungible_token.test.ts

Default `toDemical` should keep the same logic. If user provide value he is responsible for result, like if value smaller that decimals after point it will return 0.
Close https://github.com/near/near-api-js/issues/1615

feat: add optional `precision` param to control digits after decimal point
